apiVersion: v1
kind: Pod
metadata:
  labels:
    type: job
    job: jenkins-test
spec:
  containers:
  - name: podman
    image: quay.io/podman/stable
    tty: true
    command:
      - sleep
      - 1d
    securityContext:
      privileged: true
    resources:
      requests:
        cpu: "600m"
        memory: "400Mi"
