export ZSH="$HOME/.oh-my-zsh"

plugins=(git)
ZSH_THEME="gruvbox"
SOLARIZED_THEME="dark"

source $ZSH/oh-my-zsh.sh

export PATH="$PATH:$HOME/.local/bin"
export TERM=screen-256color

export FZF_DEFAULT_OPTS='--color=light,hl:12,hl+:15,info:10,bg+:4'

# Utility to set "current working directory". For each new tab or window
# you won't need to cd to the project config every time.

fbind () {
	case "$1" in
		-u)
			rm ~/.bindrc
			;;
		-c)
			if [ -f ~/.bindrc ]; then
				cd `cat ~/.bindrc`
			fi
			;;
		*)
			echo `readlink -f "$1"` > ~/.bindrc
			;;
	esac
}

fbind -c

alias nyan=nyancat
alias parrot='curl parrot.live'

alias vim='nvim'
export EDITOR=nvim

# oh-my-zsh plugin adds a alias
unalias gc
gc() {
	local commit='EDITOR=nvim git commit || bash' 
	local diff='GIT_PAGER="less -+F" git diff --staged' 

	tmux new-window "$commit" \; split-window -dh "$diff"
}
