#!/usr/bin/env bash

set -e

sudo apt-get install -y --no-install-recommends \
	build-essential python-dev cmake

echo "Plug 'Valloric/YouCompleteMe'" >> "$HOME/.config/nvim/plugin.vim"

nvim +PlugInstall +qall

"$HOME/.config/nvim/plugged/YouCompleteMe/install.py" "$@"

sudo apt-get purge python-dev cmake -y
sudo apt-get install libpython2.7 -y
