#!/usr/bin/env bash

set -ex

sudo apt-get install -y --no-install-recommends \
	build-essential python3-dev cmake

echo "Plug 'Valloric/YouCompleteMe'" >> "$HOME/.config/nvim/plugin.vim"

nvim +PlugInstall +qall

python3 "$HOME/.config/nvim/plugged/YouCompleteMe/install.py" "$@"

sudo apt-get purge python3-dev cmake -y
libpython="libpython3.$(python3 --version | cut -d . -f 2)"

sudo apt-get install "$libpython" -y
