#!/usr/bin/env bash

set -ex

sudo apt-get install -y --no-install-recommends \
	build-essential python3-dev cmake

echo "Plug 'Valloric/YouCompleteMe'" >> "$HOME/.config/nvim/plugin.vim"

nvim +PlugInstall +qall

python3 "$HOME/.config/nvim/plugged/YouCompleteMe/install.py" "$@"

sudo apt-get purge python3-dev cmake -y
libpython="libpython3.6"
if [ "$UBUNTU_RELEASE" = "focal" ]; then
	libpython="libpython3.8"
fi

sudo apt-get install "$libpython" -y
