#!/usr/bin/env bash

set -e

sudo apt-get install -y --no-install-recommends \
	build-essential python3-dev cmake

echo "Plug 'Valloric/YouCompleteMe'" >> "$HOME/.config/nvim/plugin.vim"

nvim +PlugInstall +qall

python3 "$HOME/.config/nvim/plugged/YouCompleteMe/install.py" "$@"

sudo apt-get purge python3-dev cmake -y
sudo apt-get install libpython3.6 -y
sudo apt-get install editorconfig -y
